name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Set up Python
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt 
      - name: Lint with black
        run: |
          python3 -m pip install black
          black .
        continue-on-error: true          

      - name: Test with unittest
        run: |
          python3 -m unittest tests/article_scraper_unittest.py
